---

name: "Code Quality: TypeScript"

on:
  push:

jobs:
  nodejs:
    name: Node.js
    runs-on: ubuntu-latest

    env:
      PACKAGES: "@vercel/ncc prettier"

    strategy:
      # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
      fail-fast: false
      matrix:
        node-version:
          - 20.x

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install global NPM packages
        run: npm install --global ${PACKAGES}

      - name: Install Action-specific NPM Packages
        run: npm install-clean

      - name: Build TypeScript code
        run: |
          npm run-script fmt \
          && \
          npm run-script build
